Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # Instalar Ansible dentro de la máquina virtual
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y ansible python3-pip
  SHELL

  # Asegurar que ansible y output están sincronizados
  config.vm.synced_folder "./ansible", "/home/vagrant/ansible"
  config.vm.synced_folder "./output", "/vagrant"

  # Correr el playbook desde la máquina virtual
  config.vm.provision "shell", inline: <<-SHELL
    ansible-playbook /home/vagrant/ansible/playbook.yml
  SHELL
end
