apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: actividad3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
