apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: actividad3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: us-west-1a
      containers:
        - name: postgres
          image: lemendezc/actividad3-db:1.0.0
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: db-secret
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
