apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: actividad3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: actividad3-app
  template:
    metadata:
      labels:
        app: actividad3-app
    spec:
      containers:
        - name: actividad3-app
          image: lemendezc/actividad3-app:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
