version: "3.9"
services:
  db:
    build: ./db
    container_name: actividad3-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: actividad3
      POSTGRES_USER: actividad3
      POSTGRES_PASSWORD: supersecret
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - actividad3-net

  app:
    build: ./app
    container_name: actividad3-app
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: actividad3
      DB_PASSWORD: supersecret
      DB_NAME: actividad3
    ports:
      - "3000:3000"
    networks:
      - actividad3-net

networks:
  actividad3-net:
    driver: bridge
